### ISSUE TITLE
Could you please upload also ui_database_editor.h

### ISSUE THREAD

**Issue by pengtingbit** [Kampfzwerg42/Framework-for-analysis-and-automatic-code-generation-of-Clock-Syncronization-Algorithmus#2]
Hello @Kampfzwerg42, could you please upload also ui_database_editor.h? When I tried to compile this project, this file is missing.

**Comment by Kampfzwerg42** [comment]
this file is autogenerated by qt normaly but I have created a release branch for you that include the qt generated stuff.

**Comment by pengtingbit** [comment]
Thank you. Now everything works perfectly!
